### ISSUE TITLE
Support `use stable` and friends

### ISSUE THREAD

**Issue by sandinmyjoints** [rejeep/nvm.el#1] opened 2014-12-29 07:01 UTC
Nvm [now supports commands](https://github.com/creationix/nvm#usage) such as `nvm use stable` and `nvm use system`. It would be great if nvm.el supported this syntax. Currently when I try to do `(nvm-use "stable")` I get "No such version nil".

**Comment by rejeep** [comment] 2015-01-07 09:02
Unfortunately, the [version format](https://github.com/rejeep/nvm.el/blob/master/nvm.el#L45) does not support this. Please feel free to add support for this. If not, we'll leave this issue open and I'll do it when I have time. But I'm very busy these days, so don't wait around for it.

**Comment by Fuco1** [comment] 2024-09-21 19:16
Duplicate of #7 which now has a bit more generic description so I will keep that one open

**Closed by Fuco1** 2024-09-21 19:16 UTC
